### ISSUE TITLE
Python scripts not included in package

### ISSUE THREAD

**Issue by matthewtole** [gregoiresage/pebble-localize#1]
You currently aren't including the Python scripts in the package: https://github.com/gregoiresage/pebble-localize/blob/develop/package.json#L10-L12

Makes the library a little difficult to use!

You should also probably update the documentation to include the full path of where the Python scripts will end up.

**Comment by gregoiresage** [comment]
yes sorry, I'm just making tests now with pebble packages :-p
also the code source is a fork of https://github.com/pebble-hacks/locale_framework , I'm not sure if I'm a llowed to publish this library or I let the first developers do it

**Comment by gregoiresage** [comment]
Fixed in 0.0.3
